POSTGRES_OPS_PASSWORD: ENC[AES256_GCM,data:GUCDiu5A,iv:tlzyB+8dHiX2lzCmqS9K7e8EXWvJ/XcX3TkCiogw6Y4=,tag:x+SMnptnOIJy7G2VbERRUQ==,type:str]
REDIS_OPS_PASSWORD: ENC[AES256_GCM,data:fYwiDbCA,iv:G2FjHp7O2YV2EfUotoolC5ycI7c6soh0Fq9pCXEjbrI=,tag:g5TRp6AeF5Gt1Z37mA7OfQ==,type:str]
OPS_API_PASSWORD: ENC[AES256_GCM,data:IRo0kBwX,iv:mKe48mrRrfntpZHQMrd9g+TRMCTYp4LZf4dhs3T+EPM=,tag:kwVCC06a+N4YCs6/DVcwdQ==,type:str]
OPS_PORTAL_PASSWORD: ENC[AES256_GCM,data:NsK5dbxq,iv:BadSlFL9YB5Wp5jp689xV8WGPM1O4v+Wh9ytNELFPI4=,tag:ZP5L550Mc7jKjqpckvqBIA==,type:str]
OPS_WORKER_PASSWORD: ENC[AES256_GCM,data:w4q+tbsa,iv:AmEmH1kQzOmR4VHUj2TdlYGVrq6GW1cW5A7Wb04vmbY=,tag:UunM7eMEqvIV6Ff9iMzwaA==,type:str]
REPLICA_URL: ""
HUBSPOT_TOKEN: ""
HUBSPOT_WEBHOOK_SECRET: ""
CLEVERTAP_ACCOUNT_ID: ""
CLEVERTAP_PASSCODE: ""
CLEVERTAP_REGION: ""
OMIE_APP_KEY: ""
OMIE_APP_SECRET: ""
EVOLUTION_BASE_URL: ""
EVOLUTION_TOKEN: ""
SMTP_URL: ""
GOOGLE_SA_JSON: ""
GOOGLE_ADMIN_SUBJECT: ""
OPS_PROXY_SECRET: ENC[AES256_GCM,data:NpA7XWdn,iv:ejo+Guk+MEXCUkcSa1IThs58mfOl/d3Uv/6EdCqtDfY=,tag:XrH5EypEHu2ft0xDzhoqzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upe2255ngpx6pvp0kuczvqttwwcatncyq9h2rja2nyxpcdlevphqafj7nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0dYeDFOQm5IREJ0Uy9Q
            YVhRYjZwU1BVWHFkb0xYRk1YTnQ0SFRUc1RZCjhiK2RzUjZERGxhVkx0bSsrYXdZ
            blZGaTlLeUxPMUU1SUVIeVpROHgwMncKLS0tIGlkMURGNDI1blZvTEUxQVkraFhJ
            T3FyN1htUi94QUlOblJ6bGR5akVHdVUKlzGnKQ7oJRHGZeRnU+nkPyc2cIz1Oigy
            K/sgDnc5k+nmDttpDFW34jub4JSA4vUDP09QfXYGe+P6KOIthY+WYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T21:20:28Z"
    mac: ENC[AES256_GCM,data:ygbcz9kkfyPdHCZG0htgygSMSn4/C0LtpC+eh416PVsH5qINhr6NXsopuwij2S4Ru+cVo55i5549H3AKksiNmeL7zWzEUSN/SXVshXoNyA3JUyast8GLWKVe0U/o9gDLf6cmeFK2673tFID6mQhg39KOpliDAf4IXuX47jsFDmg=,iv:J0jvjMWLSe9xgKaxeaVh4eZOaDp9mdgwCdP4TN531Ow=,tag:J/qLPKCTu8kqBRhvHcrIMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
