REPLICA_URL: ""
HUBSPOT_TOKEN: ""
HUBSPOT_WEBHOOK_SECRET: ""
CLEVERTAP_ACCOUNT_ID: ""
CLEVERTAP_PASSCODE: ""
CLEVERTAP_REGION: ""
OMIE_APP_KEY: ""
OMIE_APP_SECRET: ""
EVOLUTION_BASE_URL: ""
EVOLUTION_TOKEN: ""
SMTP_URL: ""
GOOGLE_SA_JSON: ""
GOOGLE_ADMIN_SUBJECT: ""
PULSE_API_PASSWORD: ENC[AES256_GCM,data:rfhSw532DGuGfCOA1Vp3VLnWr3MVhK1+CjcUx28XURI=,iv:kQOQtofr/G2hu0ZwTbVL6a3qfERk6eFWqibgTT/tAag=,tag:58t9Bly5+zkTzWOB0K97vg==,type:str]
PULSE_PORTAL_PASSWORD: ENC[AES256_GCM,data:glutq/k5gHsxIxYyRU/yYXLWNnqBG49pWzBg8wilZLQ=,iv:2bMffCjpn8r4IGUgyHNKMt1ae81m4irZPM+TFj8qvKU=,tag:4zZi+FFGMqGGqwc8XBQgyw==,type:str]
PULSE_WORKER_PASSWORD: ENC[AES256_GCM,data:49Wtv93QK+5mBFlbPEgzxjQsaFHOOZrX7f8AVwptSo8=,iv:rCpdSzKPEhZc6WvSpQjvarHEIdWjISSXizcpzwHyH7c=,tag:fkKzYlBp3ABUEznNHKwvOQ==,type:str]
PULSE_PROXY_SECRET: ENC[AES256_GCM,data:F3vOaRMcKzO4NgBYZCqxcDcr8+HUL5W7LlW+O2dZaJ02ExKBn9YcuW9DAwZ0XdkuFCbj61PrHtSWd+GWuxavKA==,iv:qhiBZUUvs+TSDLrpEAAjrnTgwLpc4cCZAe0cEphY0LA=,tag:n6gYe4B+LdCDE6hWkx8Kzg==,type:str]
PULSE_CHAVE_MESTRA: ENC[AES256_GCM,data:imWFqCCkdOBc6gYID32UiQRNdC0m9E8wB1K146u8Yfpv88MzuYrdjJlY4SU=,iv:NRf+2R6Vo2k0MnrbSxywKlhT1XbZu444XkqP0kUSPEk=,tag:O4haUk59RqMBXTXxWI0ZDQ==,type:str]
POSTGRES_PULSE_PASSWORD: ENC[AES256_GCM,data:+KD4lvKKu3hE+CSaYgphxou76TYbSHUg8BShU0IAJ6o=,iv:RIHaMXKXn65fhUWARvcwdldTOp6Y0y2+GoQeyhRV+50=,tag:wC6hHHdEPM2/mE/l1C4rPg==,type:str]
REDIS_PULSE_PASSWORD: ENC[AES256_GCM,data:2LAXYyT6/aX8N3w1i7KqakP4CUya/5jIM8HEenzFOMk=,iv:FY2N14D/0NqXWgaipiJ2YHndfP2MxUgbWjGGhidkwps=,tag:B06gZwvem8bHyEupOIfUnA==,type:str]
PULSE_VERIFICACAO_SEGREDO: ENC[AES256_GCM,data:57Da9oZhhX926tDYaJJ3JnHvW6GkPsmXCw2rLqPoM9kOLMIMiAzuou1CVXXwoo8xJz7PtM4Jw8RgSlhC8Lqzhw==,iv:IlhEbym201mnzlCLndvXz9mXsPgVWp9Pbg9tRYYk+gI=,tag:YR780kwXhaWshXGY8l3wLQ==,type:str]
PULSE_VERIFICACAO_EMAIL: ENC[AES256_GCM,data:NZnK1Vk=,iv:jpwghQzNOyOpt2zvT8YtLS25QUH0IzWsW0bByRusSB0=,tag:u1R3Ok0S7VXU4H0GIqrDuQ==,type:str]
GMAIL_SENDER: ENC[AES256_GCM,data:TmvtHLvJfNVDNXjn+0CiyjtuYn/oLQ==,iv:dxTYEMZUdtpzPtCNWu5+2yuljTtXPuQEyOPlQcGVmyY=,tag:x0QuD9eOsjsrslOYcVkTxg==,type:str]
GMAIL_FROM_NAME: ENC[AES256_GCM,data:fT8e43Su7XpDt9188Ntm,iv:P2cMoCUX/6n/lHaGQjwfCry1MGMOzb+kzE8igFEpZfA=,tag:qomVx59JKCPoiDj0ZxJ/Ow==,type:str]
MAIL_REPLY_TO: ENC[AES256_GCM,data:SpdZFq1P9Bkj8YtkJ87Q4Tj28LvU/A==,iv:kRmmolaxKGOsgfn/NRgyqxK29SmfwQQQPOoft3wByhg=,tag:uAhSk4nSiPBkglXxiwFMmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upe2255ngpx6pvp0kuczvqttwwcatncyq9h2rja2nyxpcdlevphqafj7nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByekRaNWNxTjh2RU1zWjJM
            VmtHWmsvOE14anMwUmNQdWlHSGE3S3JZM2hjCmxvemE4eDV2VDdNZUFYb1ZLSnJh
            Z3o2WXk2U2dlMjd0eEVZczZtQlo3TFEKLS0tIHFRZ1JkdFdVeEtibUJMS05RYWtC
            ZC9qR001dGV1L2JYV0ExZWVXeWVFaDAKNuDMVSA98QU2bWKjMAKgAJ+iq4+QkcU9
            4x/+rpMSW67jR3y6LZML39737Il+ei1s2MBuMpDqpdaJMywunvHMlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T15:27:10Z"
    mac: ENC[AES256_GCM,data:qH61tlfVROEF2/MqIiCDRjRlby4IP57TVXrCdHVVUc0+UZqgadB/tZEDl2ikqmw9VWCDyGfdDbrxnYTuInhOnSFJVNTARlZUfwNFd4EQuS50tSf655j0U7k8DqhHfH0YRxpVG3YGKBH8fpGneCkcvbfhd/aoo4y4QBobgrmxdqU=,iv:ReKyeNOv1muz2AXL9NxJ4gyT0bqRjGlnPbbQxe2IqwI=,tag:UamKfq//IkYb5xeFxLGBNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
