REPLICA_URL: ""
HUBSPOT_TOKEN: ""
HUBSPOT_WEBHOOK_SECRET: ""
CLEVERTAP_ACCOUNT_ID: ""
CLEVERTAP_PASSCODE: ""
CLEVERTAP_REGION: ""
OMIE_APP_KEY: ""
OMIE_APP_SECRET: ""
EVOLUTION_BASE_URL: ""
EVOLUTION_TOKEN: ""
SMTP_URL: ""
GOOGLE_SA_JSON: ""
GOOGLE_ADMIN_SUBJECT: ""
PULSE_API_PASSWORD: ENC[AES256_GCM,data:X1/09cHQ,iv:LZSvqKlPm6GMdLtiKR1inTlyWLH64xfM5rGIwDegHEM=,tag:Q6AQ8FNfHKutDmmwGW0CQw==,type:str]
PULSE_PORTAL_PASSWORD: ENC[AES256_GCM,data:Uyb1SiNs,iv:ukOkgpTk7Sj3FMrkwMTSzrMVMVDvSj3TJ+GqVwu2jSM=,tag:6++nhiYuOgdmsQi/Z1Sw1g==,type:str]
PULSE_WORKER_PASSWORD: ENC[AES256_GCM,data:TjNCSycu,iv:Pg+Ury4iX6ghybIBl22NEzZ7tB0EjS205NSVUEs6pzo=,tag:cvKfF6B5dULO1FdwfXgFgg==,type:str]
PULSE_PROXY_SECRET: ENC[AES256_GCM,data:SvAtkR6U,iv:inUMFmFM9Wpt50EXrRy6/Iy8t5l36ylmXXUumJTPfis=,tag:3NXgjKvX3vstGHA5MRbm+A==,type:str]
PULSE_CHAVE_MESTRA: ENC[AES256_GCM,data:nDd0H9ojmlyb383kIngzb/IYjI1YfTIaIqhPAQ9pCT+k6kbO3nHY5MbIiQQ=,iv:AV0yKipmS/qkStttMzwHgfPxW+uaBWmh9W6mXnAva6I=,tag:7qgxvtABd4DW8/2rH2rAig==,type:str]
POSTGRES_PULSE_PASSWORD: ENC[AES256_GCM,data:7Gtyz/Cp,iv:zFRcCqqOA9OP2zZKAmY60dx+6N+lxGfhhC7SPZZ+QVc=,tag:pj+C3Dl8YH+jiE1i2DaUMQ==,type:str]
REDIS_PULSE_PASSWORD: ENC[AES256_GCM,data:0lYadgL3,iv:syt73CYKtbBFHbiIN6hw9sKHSfAESRnOBMAuN3IgBnc=,tag:BUuTSMYELaGqw3ay0waA7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upe2255ngpx6pvp0kuczvqttwwcatncyq9h2rja2nyxpcdlevphqafj7nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0dYeDFOQm5IREJ0Uy9Q
            YVhRYjZwU1BVWHFkb0xYRk1YTnQ0SFRUc1RZCjhiK2RzUjZERGxhVkx0bSsrYXdZ
            blZGaTlLeUxPMUU1SUVIeVpROHgwMncKLS0tIGlkMURGNDI1blZvTEUxQVkraFhJ
            T3FyN1htUi94QUlOblJ6bGR5akVHdVUKlzGnKQ7oJRHGZeRnU+nkPyc2cIz1Oigy
            K/sgDnc5k+nmDttpDFW34jub4JSA4vUDP09QfXYGe+P6KOIthY+WYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T13:15:38Z"
    mac: ENC[AES256_GCM,data:LFgdx9k8MTjjaHliZkGf9KQsrj9fKgNR8IwvXcU8QLVXb2Jeun2JWHTRshPqreyULUAeIZXxklW5qwg3xFxr/p6T43bp7EMsWjDQX8/kBm17kEmBv5vFfww/oDG4Z6uc3QeptZ9yEWoiwvw9hKnFLyCzYTb91YxiW374ApI4GTA=,iv:Nv+TpL0ReYbeuJK/P+4jeClqHxH7YncqnVs4SioeHic=,tag:Tns4cEfT3lWvkQ3SXVUKvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
