REPLICA_URL: ""
HUBSPOT_TOKEN: ""
HUBSPOT_WEBHOOK_SECRET: ""
CLEVERTAP_ACCOUNT_ID: ""
CLEVERTAP_PASSCODE: ""
CLEVERTAP_REGION: ""
OMIE_APP_KEY: ""
OMIE_APP_SECRET: ""
EVOLUTION_BASE_URL: ""
EVOLUTION_TOKEN: ""
SMTP_URL: ""
GOOGLE_SA_JSON: ""
GOOGLE_ADMIN_SUBJECT: ""
PULSE_API_PASSWORD: ENC[AES256_GCM,data:V+VXsMZfh2qPlZk3HkoX6EzbGLmXffxUXw5znYKNJTo=,iv:VPfaOzo7hUVY4wmXnw9T4xm5jSUQbATl9sxkA0umrSE=,tag:XyDNMTW/mgZMIwelODHftg==,type:str]
PULSE_PORTAL_PASSWORD: ENC[AES256_GCM,data:NY8R1HonNJfXGZqjfiSJeebpKnuLlQya5dcN3uE54QI=,iv:T18xo7wyvNRLt5YLmePIcnHyd3Em6L3r56Oy3+IdeNg=,tag:6SUHWLRTY/yvqhKAR34xzg==,type:str]
PULSE_WORKER_PASSWORD: ENC[AES256_GCM,data:zIgCDt+1CyhdYpMqyqBrLxsh32SZZIIuuH21Fv8BWYk=,iv:MV+6wY1DsjrDyWWec7XIdnNCI8Sfxs9mrSZ4X1v+Dw4=,tag:gyxzaCKHHZe1zw02wS0sQg==,type:str]
PULSE_PROXY_SECRET: ENC[AES256_GCM,data:NWfQhvLfaTfzxTChbIb6Pi2wQONmSS+xqnq5hf8nOpzoNiyTI8yHhJnCaPtOQ82VXRFSmgCWUEvcaT1z+QKWhg==,iv:YjpIkp3/V02D/CcXT2a2ieX6uFNXiaSxemT5u3P7aqE=,tag:FIfPkM6dSdYLrFmXQx7Xrw==,type:str]
PULSE_CHAVE_MESTRA: ENC[AES256_GCM,data:nDd0H9ojmlyb383kIngzb/IYjI1YfTIaIqhPAQ9pCT+k6kbO3nHY5MbIiQQ=,iv:AV0yKipmS/qkStttMzwHgfPxW+uaBWmh9W6mXnAva6I=,tag:7qgxvtABd4DW8/2rH2rAig==,type:str]
POSTGRES_PULSE_PASSWORD: ENC[AES256_GCM,data:g314k03yLOCBgS5vlf2fKmJu4vQM5lcCGjVFoL4bxY4=,iv:DtJwCkT/duDhy5nSmJcqTggicQeR7/peVNwYER61/ew=,tag:yRqhRcnT8MuEwtcr2ZzBoA==,type:str]
REDIS_PULSE_PASSWORD: ENC[AES256_GCM,data:vUnM3iijORyjaoBx61pEb7haUZaw3f2ZhMeZmlngPyw=,iv:NTjLpk8lagLJhm8hI3WklNTZNl7/VGEA3jhV7GFgVOg=,tag:WDtZeQ5TEAQx27nAflrqmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upe2255ngpx6pvp0kuczvqttwwcatncyq9h2rja2nyxpcdlevphqafj7nz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0dYeDFOQm5IREJ0Uy9Q
            YVhRYjZwU1BVWHFkb0xYRk1YTnQ0SFRUc1RZCjhiK2RzUjZERGxhVkx0bSsrYXdZ
            blZGaTlLeUxPMUU1SUVIeVpROHgwMncKLS0tIGlkMURGNDI1blZvTEUxQVkraFhJ
            T3FyN1htUi94QUlOblJ6bGR5akVHdVUKlzGnKQ7oJRHGZeRnU+nkPyc2cIz1Oigy
            K/sgDnc5k+nmDttpDFW34jub4JSA4vUDP09QfXYGe+P6KOIthY+WYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T20:44:42Z"
    mac: ENC[AES256_GCM,data:RIxuiaGSDcJLJ+1CRzmSqSH4HBCqA/Dd7ucdKozyEH8O+C+57Ztyjm2jPYFA52ZMfz18dG491PiSxc3Gsr3tEocfHM6waGyAH3RM6o/xFtMvB8TZvIIunQXhnkdnlX8dOd1AvGrzhE5a50tfh9vM7eHMJfAyq6zRrbgxmfiEdk0=,iv:hndUT+D4BOzMAj0D4eVsRj7u17OTNhJeXiLJHZuw0hY=,tag:JM78CriS0Ze9oxFCYFyP7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
